---
- name: Reboot after CUDA installation
  ansible.builtin.reboot:
    reboot_timeout: 600
    pre_reboot_delay: 10
    post_reboot_delay: 30
  listen: "Reboot after CUDA installation"

- name: Wait for system to come back online
  ansible.builtin.wait_for_connection:
    delay: 30
    timeout: 300
  listen: "Wait for system to come back online"
