---
- name: Check if local Hugging Face token exists
  ansible.builtin.stat:
    path: "~/.cache/huggingface/token"
  register: local_hf_token
  delegate_to: localhost
  become: false

- name: Create .cache/huggingface directory on remote
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.cache/huggingface"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
  become: true
  become_user: "{{ ansible_user }}"

- name: Copy Hugging Face token to remote host
  ansible.builtin.copy:
    src: "~/.cache/huggingface/token"
    dest: "/home/{{ ansible_user }}/.cache/huggingface/token"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'
  become: true
  become_user: "{{ ansible_user }}"
  when: local_hf_token.stat.exists

- name: Check if local Hugging Face stored_tokens exists
  ansible.builtin.stat:
    path: "~/.cache/huggingface/stored_tokens"
  register: local_hf_stored_tokens
  delegate_to: localhost
  become: false

- name: Copy Hugging Face stored_tokens to remote host (if exists)
  ansible.builtin.copy:
    src: "~/.cache/huggingface/stored_tokens"
    dest: "/home/{{ ansible_user }}/.cache/huggingface/stored_tokens"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'
  become: true
  become_user: "{{ ansible_user }}"
  when: local_hf_token.stat.exists and local_hf_stored_tokens.stat.exists

- name: Verify Hugging Face authentication
  ansible.builtin.command: "{{ venv_path }}/bin/python -c 'from huggingface_hub import whoami; print(whoami())'"
  register: hf_auth_check
  become: true
  become_user: "{{ ansible_user }}"
  when: local_hf_token.stat.exists
  failed_when: false
  changed_when: false

- name: Display Hugging Face authentication status
  ansible.builtin.debug:
    msg: |
      🤗 Hugging Face Authentication Status:
      {% if local_hf_token.stat.exists %}
      ✅ Token copied from local host
      {% if hf_auth_check.rc == 0 %}
      ✅ Authentication verified: {{ hf_auth_check.stdout }}
      {% else %}
      ⚠️  Authentication check failed. You may need to login manually with: hf auth login
      {% endif %}
      {% else %}
      ⚠️  No local token found. Please run 'hf auth login' on the remote host after setup.
      {% endif %}
